### ISSUE TITLE
[MVP] Main Menu "Options" Page

### ISSUE THREAD

**Issue by FrancisTR** [FrancisTR/Godot-Purified#20]
In the main menu, where there is a "Options" button:

- Create a new scene for the Options page.
- In that new scene add accessibility such as button mapping, master sound volume, etc. (You can add other accessibility if you have time).
- Make sure to have a "Back to menu" button.

**Comment by FrostyNick** [comment]
I can work on this

**Comment by FrancisTR** [comment]
@FrostyNick Reopening this issue since there are enhancements you have been adding. Couple things that needs to be fixed:

- Ensure that the mapping is unique. Meaning that there cannot be two "W" keys doing left and right movement for example.
- A separate scene where if the player click "ESC" during game, it will bring the options menu that is NOT the main menu Options menu. This is a separate scene that is the exact same as the options menu, but when I click "Back", it brings me back to the game and NOT the main menu.

Let me know what you think. Once I made my changes tonight, feel free to implement :)
