### ISSUE TITLE
[MVP] Sounds for Character and the Environment

### ISSUE THREAD

**Issue by FrancisTR** [FrancisTR/Godot-Purified#24]
We need a giant list of sounds for not only the character, but the environment as well. I expect this to have a lot of replies in this issue.

For character, it can be different walking sound when the character is walking on grass VS on stone. For the environment, it can be as simple as adding a background theme music in the background or the sound of the water.

Reply to this issue of the list of sounds you found/made with the following:

- Is this sound for the character or other?
- Attach the file of the sound.

**Comment by johntran038** [comment]
I can help

**Comment by FrostyNick** [comment]
Just a note that there are currently 12 walking sounds -- 6 sounds for each material (Stone and sand) -- which are in `GodotGame/Assets/Sounds`. I put these in the project awhile ago. I didn't make these though, they are in public domain so additional sounds could be welcome as well to add onto, replace the sounds, or leave the sounds as is.

I can work on inventory sounds, I was looking into making a few sounds for that.

**Comment by johntran038** [comment]
Okay, for the inventory system I wanted the design to be like you're looking inside of a brief case for items, so if you could make sounds for that, that would be great!

**Comment by FrostyNick** [comment]
[toggleInventorySounds.zip](https://github.com/FrancisTR/Godot-Purified/files/14656596/toggleInventorySounds.zip)

Sound file names:
closeBriefcase.ogg
openBriefcase1.ogg
openBriefcase2.ogg

That's the closest I could get to brief case sounds I think. GitHub doesn't let me upload the sounds directly here, so it's in a zip file.
