### ISSUE TITLE
[MVP] Investigate on adding voice into dialogue

### ISSUE THREAD

**Issue by FrancisTR** [FrancisTR/Godot-Purified#27]
- Need information on how dialogue works with voice enabled in Godot.
- Need confirmation on how we should add accessibility in this case.

**Comment by not-thien** [comment]
You can assign this to me, I'll look into it

**Comment by not-thien** [comment]
Completed with details and steps, with references to documentation & tutorials [here](https://docs.google.com/document/d/1VvjqTu2vxNp0hOP4-FMJqlkAfE1od7TRwHOyd2w_h58/edit?usp=sharing)
