### ISSUE TITLE
[MVP] Mask collision of assets

### ISSUE THREAD

**Issue by FrancisTR** [FrancisTR/Godot-Purified#31]
This issue is basically going to be a list of assets that are needed to have collision. If you know an asset that needs collision or it needs the collision to be resize, please comment in this issue with:

- What asset is it?
- Need collision or need a collision resize?

**Comment by not-thien** [comment]
Will do, assign to me

**Comment by not-thien** [comment]
Completed with screenshots and details on this doc [linked here](https://docs.google.com/document/d/1S54cqzh-nITYVYcAr7oSNYKU3rC_EHdYiOTzbS7Pzss/edit?usp=sharing)

**Comment by FrancisTR** [comment]
@not-thien This looks great. This issue will be open until the end of the MVP stage since it is possible that the map will change, meaning more testing. I will keep you updated on that and will let you know!
