### ISSUE TITLE
[Prototype] Display what day is it on the screen

### ISSUE THREAD

**Issue by FrancisTR** [FrancisTR/Godot-Purified#4]
The game displays the number of days it has been for the player.

- Show "Day 1" through "Day 10" on the top right of the screen

- If the player goes to some "exit" (going out of the town they are in), then the day will change. For example, if they are on Day 3 and they decide to walk out of the town, it will then change from Day 3 to Day 4

- For each day, the scenery changes. For example, the block is blue on Day 1. Then on Day 2, it changes to Red

- If the player reaches Day 10 and then exit, show some ending. After that, bring the user to the main menu

**Comment by johntran038** [comment]
let me try this one

**Comment by johntran038** [comment]
**Questions:**
Why would the day change when the player goes to some "exit" and how would that work?
- Would it be possible for the player to exit multiple times in a row and immediately run out of time?
Because its a story driven, wouldn't it be better if the player choose to end the day?
-ex: after a certain point, the npcs will no longer have any dialogue and will go to bed, because there is nothing left to do, the player can go to bed at the village / go home and then to bed to end the day

**Comment by FrancisTR** [comment]
> **Questions:** Why would the day change when the player goes to some "exit" and how would that work?
> 
> * Would it be possible for the player to exit multiple times in a row and immediately run out of time?
>   Because its a story driven, wouldn't it be better if the player choose to end the day?
>   -ex: after a certain point, the npcs will no longer have any dialogue and will go to bed, because there is nothing left to do, the player can go to bed at the village / go home and then to bed to end the day

Hey @johntran038. 

1. By exit, I mean that the player walks away from the village since he is an employee and does not live there. If he were to leave the village, it then goes to the next day and it rinse and repeats. The player would not be able to leave the village IF he has talk to a good certain number of people. Otherwise, there will be a message stating that you need to talk to the people and such. The player can stay at the village as long as they want (meaning that I can AFK on Day 1 for 3 hours for no good reason). Don't worry about that detail yet since I only want to have the functionality there and would be easy to build on once we have that (since it seems you have done it already. Nice work).

2. As stated in the first point, there will be a condition that needs to be met in order for the player to exit. Right now, the player can exit as many times as the player wants for now. Once I added the dialogue part, you can experiment on that if you like.

3. Again, conditions need to be met in order to exit the village.


Let me know if there are any questions or clarification :)
