### ISSUE TITLE
[Prototype] Crafting System?

### ISSUE THREAD

**Issue by FrancisTR** [FrancisTR/Godot-Purified#7]
- Display the amount of currency the player has somewhere on the screen that deems appropriate
- Have some kind of block on the field. When the player approaches it, show a list of items they can build with a cost. If they purchase some item, automatically placed it on screen (This will be treated as a building)

**Comment by not-thien** [comment]
Still need completion? Can fork and work on this if needed @FrancisTR

**Comment by FrancisTR** [comment]
@not-thien Sup Thien. You can work on this! The group has decided that this should work as the following:

- There is a visible sprite (Broken well) on the map. 

- When the player approaches the broken well, it will prompt you a list of certain items required to fix the well (like wood and stone for example. To keep it simple, just make a pop up with a list of things needed). 

- The player must have items in their "inventory" (To keep it simple, make a indicator of how much items they have on the top left of the screen. For example, it can show "Wood: 3" on the top left). Because of the item requirements, make it where the player will pick up the item if they approach it automatically (Place wood on the map and the player picks it up like an item).

- If the player meets the requirement to fix the broken well, show in the pop up that they can "fix" the well. For example, the button on the pop up does not appear if they don't have enough resources. If they do have enough resources, the button will be visible in the popup to the user. When clicked, the sprite changes from a broken well to a fixed well (If you don't have the sprite for the broken well and the well, just use any placeholder images of your choice as long as it appears different when the "fix the well" button is clicked).



That's it. If it can be done by this weekend, that would be great because I am planning on tie in everything together to make it a playable prototype since next week is Game Jam week. Do let me know here if any questions.
